### ISSUE TITLE
wemo has changed its connection system

### ISSUE THREAD

**Issue by quizatsaderac** [homebridge-plugins/homebridge-platform-wemo#181]
**Is your feature request related to a problem? Please describe.**

wemo has changed its connection system.

it is now necessary to create a wemo account with email and password to be able to use the accessories.
I think that an update of the plug in is necessary

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rcoletti116** [comment]
I, for one, am going to hold off and avoid their account system as long as possible. I've never had an issue with the current set up, and based on twitter activity they've made a mess with the latest app update. That said, I am curious about the direction of this plugin with this news and whether it can support both old and new methods.

**Comment by loudgazelle** [comment]
the account system is required if you want to add a new device to the wemo app, or if you reset an existing device and try to add it back to the app. I discovered this after resetting a wemo bulb. I think this means that the plugin will need to be updated to allow for the login option because they force you to use it in order to reset existing devices or add new devices. 

@rcoletti116 is right when he said that they've made a mess with the latest app update. They promise better connectivity to devices with this update and the behavior I've experienced is the exact opposite - half of my devices regularly do not show up in the app now, before this update I would have at most one or two devices that failed to communicate, and most of the time they all communicated. 

The app also makes it impossible for me to register for a new account, sign in using my existing belkin or nectam accounts, or reset the password for those accounts. There's literally no way that I've found to get that part of the app working, so I'm stuck with this reset bulb being a plain old light bulb.

**Comment by twynne** [comment]
Having the same issues. Bizarrely the plugin seemed to continue working initially, but maybe I imagined it!

Does anyone know once an account  hasBeen created if you can go back?

**Comment by loudgazelle** [comment]
I bit the bullet and created the login, nothing seems to have changed with regard to the API access. I think the "security" benefit that they've added only pertains to wemo apps - meaning that someone can't hop on my network and use their wemo app to control my devices without having my login. They could, however, hop on my network and control my devices via the API.

**Comment by quizatsaderac** [comment]
all seem to be working fine now. the wemo app and the pugin hombridge and apple home :)

**Comment by LordZork** [comment]
Can someone explain how to get devices connected to/through the plugin, and into HomeKit (into the Home app), once the plugin is installed?  

It is my understanding that newer Wemo devices support HomeKit, but I have an older device that I am trying to get into HomeKit (into the Home app) via Homebridge and this plugin.  But, it is not clear what to do after installing the plugin, and nothing showed up in the Home app even though the device is setup and working within the Wemo app.

Is there something that needs to be down with an account, or having or signing into an account, or with ports or anything like that?

Any help would be greatly appreciated, thanks!

**Comment by quizatsaderac** [comment]
no, just add these lines ( the 2 lines Wemo)in config.json as in the example:
    {
            "name": "Belkin WeMo",
            "platform": "BelkinWeMo"
        },
        {
            "platform": "ControlChromecast",
            "name": "Chromecast"

wemo accessories are automatically recognized.

**Comment by LordZork** [comment]
@quizatsaderac, Chromecast?  Is that for someone else, or a response to me.  The Wemo accessories didn't automatically get recognized that I could tell.

**Comment by quizatsaderac** [comment]
It is a part of my config.json for example.
Do you have this 2 lines in your config.json
{
"name": "Belkin WeMo",
"platform": "BelkinWeMo"
}
I had to add them manually for the plugin to work

**Comment by LordZork** [comment]
@quizatsaderac Yes, those lines were/are added.  Still nothing.
